name: dependencies
on:
  issue_comment:
    types: [ created, deleted ]

env:
  WORKING_DIR: template

jobs:
  create_issue:
    name: Create Dependencies Report
    id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
          ref: ${{ steps.pr_data.outputs.branch }}
          
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/${{ env.WORKING_DIR }}/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: echo "dependencies=$(./gradlew dependencyUpdates)" >> $GITHUB_ENV

      - name: Create Dependencies issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "filmaluco"
          labels: "dependencies"
          title: "Dependencies with update Available"
          body: |
            ${{ env.dependencies }}
          pinned: true
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}