on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/${{ env.WORKING_DIR }}/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: ./gradlew dependencyUpdates

      - name: HTML Preview
        working-directory: ${{ env.WORKING_DIR }}
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: build/dependencyUpdates/report.html